set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR i686 CACHE STRING "System Processor")
set(MSYS 1)
set(CMAKE_CROSS_COMPILING ON)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TOOLCHAIN_PREFIX i686-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX} CACHE PATH "List of root paths to search on the filesystem")
set(CMAKE_PREFIX_PATH /usr/${TOOLCHAIN_PREFIX} CACHE PATH "List of directories specifying installation prefixes to be searched")
set(CMAKE_INSTALL_PREFIX /usr/${TOOLCHAIN_PREFIX} CACHE PATH "Installation Prefix")

set(CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES /usr/${TOOLCHAIN_PREFIX}/include)
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /usr/${TOOLCHAIN_PREFIX}/include)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc-posix)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
set(CMAKE_Fortran_COMPILER ${TOOLCHAIN_PREFIX}-gfortran-posix)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_SYSTEM_PREFIX_PATH /usr/${TOOLCHAIN_PREFIX}/qt5 ${CMAKE_SYSTEM_PREFIX_PATH})
