set(CMAKE_SYSTEM_NAME "Windows")
set(CMAKE_SYSTEM_PROCESSOR x86_64 CACHE STRING "System Processor")
set(MSYS 1)
set(CMAKE_CROSS_COMPILING ON)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(TOOLCHAIN_PREFIX x86_64-w64-mingw32)

set(CMAKE_FIND_ROOT_PATH /usr/${TOOLCHAIN_PREFIX} CACHE PATH "List of root paths to search on the filesystem")
set(CMAKE_PREFIX_PATH /usr/${TOOLCHAIN_PREFIX} CACHE PATH "List of directories specifying installation prefixes to be searched")
set(CMAKE_INSTALL_PREFIX /usr/${TOOLCHAIN_PREFIX} CACHE PATH "Installation Prefix")

set(CMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES /usr/${TOOLCHAIN_PREFIX}/include)
set(CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES /usr/${TOOLCHAIN_PREFIX}/include)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc-posix)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++-posix)
set(CMAKE_Fortran_COMPILER ${TOOLCHAIN_PREFIX}-gfortran-posix)
set(CMAKE_RC_COMPILER ${TOOLCHAIN_PREFIX}-windres)

set(CMAKE_SYSTEM_PREFIX_PATH /usr/${TOOLCHAIN_PREFIX}/qt5 ${CMAKE_SYSTEM_PREFIX_PATH})


SET( KWSYS_CHAR_IS_SIGNED
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_HAS_SLICED_DESTRUCTOR_BUG
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_HAS_SLICED_DESTRUCTOR_BUG__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_HAS_WORKING_STRINGSTREAM
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_HAS_WORKING_STRINGSTREAM__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_HAS_LFS
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_HAS_LFS__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VXL_SSE2_HARDWARE_SUPPORT_POSSIBLE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VXL_SSE2_HARDWARE_SUPPORT_POSSIBLE__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_COMPLEX_POW_WORKS
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_COMPLEX_POW_WORKS__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_CHAR_IS_SIGNED
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_CHAR_IS_SIGNED__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_NUMERIC_LIMITS_HAS_INFINITY
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_NUMERIC_LIMITS_HAS_INFINITY__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VCL_PROCESSOR_HAS_INFINITY
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VCL_PROCESSOR_HAS_INFINITY__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( QNANHIBIT_VALUE
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( QNANHIBIT_VALUE__TRYRUN_OUTPUT
     "-DTEEM_QNANHIBIT=1"
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( KWSYS_LFS_WORKS
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( KWSYS_LFS_WORKS__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
SET( VXL_HAS_SSE2_HARDWARE_SUPPORT
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( VXL_HAS_SSE2_HARDWARE_SUPPORT__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( DOUBLE_CONVERSION_CORRECT_DOUBLE_OPERATIONS__TRYRUN_OUTPUT
     "89255.0/1e22 = 8.9255e-018"
     CACHE STRING "Output from TRY_RUN" FORCE)
set( HDF5_PRINTF_LL_TEST_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT
     "PRINTF_LL_WIDTH=[I64]"
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_LDOUBLE_TO_INTEGER_WORKS_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_ULONG_TO_FLOAT_ACCURATE_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_FP_TO_ULLONG_ACCURATE_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_LDOUBLE_TO_UINT_ACCURATE_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_LLONG_TO_LDOUBLE_CORRECT_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( H5_NO_ALIGNMENT_RESTRICTIONS_RUN
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( C_CHAR_SIGNED
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( C_CHAR_SIGNED__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( HAVE_IOEO_EXITCODE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( _OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE
     "1"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( _OPENTHREADS_ATOMIC_USE_GCC_BUILTINS_EXITCODE__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
set( POPPLER_HAS_CAIRO_EXITCODE
     "0"
     CACHE STRING "Result from TRY_RUN" FORCE)
set( POPPLER_HAS_CAIRO_EXITCODE__TRYRUN_OUTPUT
     ""
     CACHE STRING "Output from TRY_RUN" FORCE)
